export const userTypes = {
    LOGIN_USER: 'CREATE_USER',
    LOGOUT_USER: 'LOGOUT_USER',
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    UPDATE_PHOTO: ' UPDATE_PHOTO',
    TOGGLE_ERROR: 'TOGGLE_ERROR',
    HANDLE_FAVORITES: 'HANDLE_FAVORITES'
}